halo-dev/theme-earth

.gitignore, Makefile, README.md, build.gradle
Add build script into Makefile to build the theme conviniently. See README.md for more.
/kind feature
```release-note
None
```
=> Add build script into Makefile

templates/modules/footer.html
What type of PR is this?
/kind bug
What this PR does / why we need it:
修复页脚 Logo 显示不正确的问题。
Which issue(s) this PR fixes:
Fixes https://github.com/halo-dev/halo/issues/2894
Does this PR introduce a user-facing change?
```release-note
修复页脚 Logo 显示不正确的问题。
```
=> fix: Logo is not displayed properly

package.json, theme.yaml
发布 1.1.0。
```release-note
None
```
=> chore: release 1.1.0

templates/error/error.html
修复异常页面无法正常渲染的问题。
/kind bug
```release-note
None
```
=> fix: error template render

package.json, theme.yaml
发布 1.1.1
```release-note
None
```
=> chore: release 1.1.1

templates/modules/footer.html
What type of PR is this?
/kind bug
What this PR does / why we need it:
修复页脚风格二 Logo 显示不正确的问题。
Which issue(s) this PR fixes:
Fixes [halo-dev/halo#2894](https://github.com/halo-dev/halo/issues/2894)
Does this PR introduce a user-facing change?
```
none
```
=> fix: Footer Style 2 Logo is not displayed properly

templates/page.html, templates/post.html
支持同时判断文章是否允许评论以及全局是否允许评论。
Fixes #45 
Fixes https://github.com/halo-dev/theme-earth/issues/38
/kind feature
```release-note
None
```
=> feat: add supports for disabled comment

templates/modules/header.html
Fixes #51
```release-note
修复在部分浏览器中顶部 Logo 的宽度问题
```
=> fix: logo width issue in some old browser

package.json, theme.yaml
发布 1.2.0。
Fixes #55 
/kind  improvement
```release-note
None
```
=> chore: release 1.2.0

templates/page.html
修复自定义页面无法正常渲染的问题。
/kind bug
Fixed #59 
```release-note
修复自定义页面无法正常渲染的问题。
```
=> fix: single page not working

package.json, theme.yaml
发布 1.2.1
```release-note
None
```
=> chore: release 1.2.1

templates/post.html
/kind feature
固定了文章目录。
Ref #49 
1、粘性位置，距离顶部5rem，z层50
2、目录最大高度为10rem
```release-note
固定了文章目录栏。
```
=> feat: add sticky supports for post toc

templates/modules/header.html, templates/page.html, templates/post.html
修改文章和页面编辑按钮的地址指向，用于适配 https://github.com/halo-dev/halo/pull/4005
```release-note
修改文章和页面编辑按钮的地址指向，适配 Halo 2.6 中的 Console 路由模式。
```
=> refactor: change the url of the post editing route

templates/page.html, templates/post.html, theme.yaml
修改评论功能是否可用的判断方式。
see https://github.com/halo-dev/halo/pull/4271
```release-note
修改评论功能是否可用的判断方式。
```
=> refactor: comment visible condition

templates/moments.html
Fixes #120 
```release-note
为瞬间页面的头像设置默认头像。
```
=> fix:add moment default avatar

templates/modules/footer.html
提高Accessibility
```release-note
为部分图片添加 alt 属性，提升可访问性。
```
=> Add alt attribute to gongan_beian image

templates/modules/footer.html
```release-note
优化页脚文字在暗色模式下的样式
```
=> feat: update footer text color in dark mode

templates/modules/widgets/profile.html
添加aria-label字段，提高Accessibility评分
```release-note
None
```
=> feat: improve accessibility of profile widget

theme.yaml
更新 theme.yaml 描述文件。
1. 使用 homepage 代替 website，website 字段将在未来废弃，see https://github.com/halo-dev/halo/pull/4061
2. 添加 license 字段。
```release-note
None
```
=> chore: update theme.yaml

theme.yaml
为 theme.yaml 添加 issues 字段，适配：https://github.com/halo-dev/halo/pull/5755
```release-note
为 theme.yaml 添加 issues 字段
```
=> feat: add issues field for theme manifest

templates/modules/sidebar.html
修复文章侧边栏中目录移动问题
```release-note
None
```
=> fix: fix sidebar content scrolling issue in article table of contents

package.json, templates/modules/footer.html, templates/modules/post-card.html, templates/modules/share-modal.html, templates/moments.html, templates/page.html, templates/post.html
这个pr修复了不可用的 prettier 脚本
顺便跑了一遍 prettier
https://github.com/guqing/halo-theme-higan/pull/91#issuecomment-2058935471
```release-note
None
```
=> chore: fix unavailable prettier task config

.husky/pre-commit, package.json, pnpm-lock.yaml
引入 husky 和 lint-staged，实现在提交代码前格式化修改的代码。
```release-note
None
```
=> chore: integrate husky and lint-staged for pre-commit code formatting

settings.yaml, templates/post.html
支持隐藏文章的点赞和分享按钮。
/kind feature
Fixes https://github.com/halo-dev/theme-earth/issues/158
```release-note
支持隐藏文章的点赞和分享按钮。
```
=> feat: add support for hiding upvote and share buttons on posts

templates/modules/footer.html
=> refactor: add condition for icp config

templates/modules/layout.html
添加回到顶部按钮的aria-label值，提高无障碍评分
```release-note
None
```
=> feat: improve accessibility of scroll-to-top button

templates/modules/featured-post-card.html, templates/modules/post-card.html, templates/moments.html, templates/photos.html, theme.yaml
适配 Halo 2.19，支持响应式图片。
/kind feature
```release-note
适配 Halo 2.19，支持响应式图片。
```
=> feat: add supports for responsive image

templates/links.html
Fixes https://github.com/halo-dev/theme-earth/issues/182
```release-note
链接页面支持显示评论区
```
=> feat: add comment widget supports for links page

templates/modules/header.html
=> refactor: redirect to current url after login

templates/modules/footer.html
```release-note
修复只填写了 ICP 备案号时不显示的问题
```
=> Fix the problem of not displaying while configuring ICP only

templates/modules/layout.html
为 Logo 资源添加 preload 标签，缓解因为图片加载而导致的 CLS 问题。
/kind feature
```release-note
为 Logo 资源添加 preload 标签，缓解因为图片加载而导致的 CLS 问题。
```
=> feat: add preload tag for logo image

templates/modules/category-tree.html, templates/modules/tag-filter.html, templates/modules/widgets/tags.html
/kind bug
```release-note
修复分类列表中的文章数量可能不显示的问题。
```
=> fix: missing post count display in category listing

settings.yaml, templates/modules/header.html
支持设置文字 Logo 类型。
Fixes https://github.com/halo-dev/theme-earth/issues/134
```release-note
支持设置文字 Logo 类型。
```
=> feat: add logo type setting option

i18n/en.properties, i18n/es.properties, i18n/zh_CN.properties, i18n/zh_TW.properties, templates/categories.html, templates/modules/category-filter.html
添加 /categories 模板。
/kind feature
Fixes https://github.com/halo-dev/theme-earth/issues/121
```release-note
添加 /categories 模板。
```
=> feat: add categories template

templates/modules/pagination.html
```release-note
添加底部分页选择的背景颜色。
```
=> fix: add styling to pagination dropdown options

templates/modules/category-tree.html, templates/modules/tag-filter.html, templates/modules/widgets/tags.html
修复分类下文章数量显示不正确的问题。
See https://github.com/halo-dev/halo/issues/7095
/kind bug
```release-note
修复分类下文章数量显示不正确的问题。
```
=> fix: correct post count display in categories

templates/page.html
```release-note
解决单页面冗余加载 github-markdown.css 的问题
```
=> fix: resolve redundant github css loading on singlePage

settings.yaml, src/styles/main.scss, templates/doc-catalog.html, templates/doc.html, templates/docs.html, templates/modules/base-head.html, templates/modules/doc-layout.html
Fixes #249 
```release-note
适配 Docsme 插件
```
=> Add supports for docsme plugin
