halo-dev/theme-earth

- settings.yaml
- templates/modules/footer.html
在大陆上线的站点都需要在底部显示备案信息，目前这个主题没有相关显示信息及对应配置。
在主题底部增加了 ICP 备案号显示，并增加了 `ICP备案号` 及 `ICP备案跳转链接` 两个配置。当不配置备案号时，底部显示内容与修改前相同。
```release-note
feat: 增加底部备案信息及对应设置
```
> feat: 增加底部备案信息及对应设置

- templates/page.html
当作者没有设置头像时不显示图片，与文章模板保持一致。
修改前：
修改后：
> fix: 作者头像未设置时在自定义页面不显示

- templates/category.html
- templates/index.html
- templates/modules/featured-post-card.html
- templates/modules/post-card.html
- templates/modules/tag-filter.html
- templates/modules/widgets/tags.html
- templates/page.html
- templates/post.html
- templates/tag.html
- templates/tags.html
使用 Thymeleaf 的 [Literal substitutions](https://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#literal-substitutions) 特性优化 th:class 和 th:text 标签的字符串拼接写法，一定程度上可以让代码提升阅读性。它的写法类似于 JavaScript 的 [Template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)。
```release-note
None
```
> refactor: use literal substitutions to improve th:class and th:text

- templates/links.html
修复链接页面（/links）的链接没有绑定访问地址的问题。
/kind bug
Fixes https://github.com/halo-dev/theme-earth/issues/35
```release-note
None
```
> fix: links of links page are not bound url

- templates/modules/footer.html
在页脚添加 `<halo:footer />` 标签，修复在后台注入页脚代码不生效的问题。
```release-note
在页脚添加 `<halo:footer />` 标签，修复在后台注入页脚代码不生效的问题。
```
> feat: add halo:footer tag

- templates/modules/post-card.html
Fixed #53 
- 去掉了post-card的“cursor-pointer”，这样鼠标指针移入post-card只有可点击时才会显示“手指”
```release-note
移除文章卡片最外层的手型鼠标样式。
```
> perf: remove pointer cursor style for post card container

- templates/modules/footer.html
解决自定义页脚标题设置之后不生效的问题。
自定义页脚标题后，
Ref #69 
做了一个判断，若页脚标题设置了且不为空，则启用自定义的页脚标题，否则显示站点标题。
```release-note
none
```
> fix the problem that the footer title does not display

- templates/post.html
稍微加大了文章目录的长度。
Fixes #77 
目录高度自适应，最大高度从max-h-40到max-h-64
```release-note
文章目录最大高度变大
```
> feat: increased the length of the post toc widget

- templates/post.html
fix #84 
https://tailwindcss.com/docs/z-index#arbitrary-values
> If you need to use a one-off z-index value that doesn’t make sense to include in your theme, use square brackets to generate a property on the fly using any arbitrary value.
> fix: fix the post sidebar_prepend zindex

- theme.yaml
添加应用市场 ID 的 annotation，方便在首次初始化 Halo 之后可以在应用市场检测后续的更新。
```release-note
添加应用市场的 App ID 字段，使其可以在内置的应用市场检测新版本。
```
> chore: add app id annotation

- templates/page.html
- templates/post.html
修复文章和页面中点击评论图标无法跳转到评论区域的问题。
/kind bug
```release-note
修复文章和页面中点击评论图标无法跳转到评论区域的问题。
```
> fix: comment area anchor not working

- templates/modules/hero.html
修复文章封面图包含一个 * 字符的问题。
/kind bug
```release-note
修复文章封面图包含了一个 * 字符的问题。
```
> fix: post cover css

- templates/moments.html
- templates/page.html
- templates/post.html
移除评论组件代码注入的 colorScheme 参数，在最新的评论插件中，已经可以通过 css 变量来控制配色，所以此参数不再有效。
/kind cleanup
```release-note
None
```
> chore: cleanup inject code of comment widget

- templates/modules/footer-social.html
- templates/modules/image-view-modal.html
- templates/modules/widgets/profile.html
侧边站点资料卡片的社交媒体支持图片形式的打开方式。
/kind feature
Fixes #133 
```release-note
侧边站点资料卡片的社交媒体支持图片形式的打开方式。
```
> feat: add support for image formats to social media settings

- templates/modules/share-modal.html
修复分享弹窗中链接过长导致的样式问题。
Fixes https://github.com/halo-dev/theme-earth/issues/141
/kind bug
```release-note
修复分享弹窗中链接过长导致的样式问题。
```
> fix: resolve link display issue in share modal

- settings.yaml
Fixes #166 
```release-note
修复首屏标题文字颜色默认值不生效的问题。
```
> fix: resolve issue with default title text color not being applied

- templates/modules/footer.html
Resolve issue with footer menu items not displaying
/kind bug
Fixes #168 
```release-note
修复页脚菜单项名称可能不显示的问题。
```
> fix: resolve issue with footer menu items not displaying

- templates/modules/header.html
为菜单子目录添加 `dark:divide-slate-600`，使其在暗色模式下表现正常
```release-note
None
```
> feat: refine dark mode for menu divider

- templates/modules/layout.html
支持动态设置 HTML 的 lang 属性。
BTW，这个改动只是暂时这样做，因为这个 lang 属性的定义可能是 publisher language，而不是根据用户访问的语言来确定，比如一个完全是中文内容的网站，如果设置为了 en，那么部分字符可能发生改变。不过 Halo 暂时没有设置发布语言的设置项，所以暂时这样做问题也不大。
/kind feature
```release-note
支持动态设置 HTML 的 lang 属性。
```
> feat: support dynamic html language attribute

- templates/modules/footer.html
修复页脚菜单项链接没有设置 target 的问题。
/kind bug
Fixes https://github.com/halo-dev/theme-earth/issues/202
```release-note
修复页脚菜单项链接没有设置 target 的问题。
```
> fix: add target attribute to footer menu links

- templates/modules/category-filter.html
修复首页分类筛选项在移动端的访问性问题。
Fixes https://github.com/halo-dev/theme-earth/issues/201
```release-note
修复首页分类筛选项在移动端的访问性问题。
```
> fix: improve category filter accessibility on mobile devices

- i18n/zh_CN.properties
- src/alpine-data/color-scheme-switcher.ts
- templates/modules/header.html
优化配色切换逻辑，改为使用下拉框切换。
```release-note
优化配色切换逻辑，改为使用下拉框切换。
```
> refactor: improve color scheme switcher

- i18n/zh_CN.properties
修复中文语言中 `下一页` 的文字错误。
/kind bug
```release-note
修复中文语言中 `下一页` 的文字错误。
```
> fix: correct Chinese translation for pagination 'next page' text

- templates/modules/hero.html
fix: update subtitle opacity for better visibility in hero module, close #129 
```release-note
修复首页副标题显示不明显的问题。
```
> fix: update subtitle opacity for better visibility in hero module

- src/main.ts
- src/styles/main.scss
Close: #227
移除 tocbot 初始化配置中关于滚动相关的配置，交给浏览器原生行为处理。可以解决使用锚点链接定位未偏移问题。
已在测试如下3中场景，均可正常跳转偏移：
- 直接通过URL访问带hash的链接
- 点击页面内的锚点链接
- 点击目录项
```release-note
修复直接访问文章无法使用目录定位的问题。
```
> fix: resolve the issue of anchor link positioning not being offset

- src/main.ts
```release-note
修复文章目录激活项偏移错误的问题
```
> fix: correct offset for active toc item

- templates/modules/pagination.html
```release-note
修复在 pagination 不存在时添加事件监听器的问题
```
> fix: add null check for pagination element before adding event listener

- templates/archives.html
- templates/categories.html
- templates/tags.html
为了提升代码的可维护性和一致性，将 tags.html、categories.html 和 archives.html 中的自定义分页逻辑替换为统一的分页模块。这样可以减少重复代码，并简化未来的维护工作。
```release-note
None
```
> Refactor paginations

- templates/post.html
before:
after:
```release-note
调整文章页面标签列表的下边距，以更好的适应内容。
```
> Adjust bottom margin of tag list on post page
